# Car Price Case

## Background

### Why Data Analysis
- Data is everywhere
- Data analysis/data science helps us answer questions
- Predicting future or the unknown

### Problems
- Tom wants to sell his car, but he doesn't know how much money should he sell his car?
- The price he sets should not be too high, but not too low either. How can we help him? 
- As a data analyst, we should ask these questions:
  - Is there data on the prices of other cars and their characteristics? 
  - What features of cars affect their prices?
    - Color? Brand? Horsepower? Something Else? 
  - Asking the right questions in terms of data!

## Data Load

In [88]:
import pandas as pd
import numpy as np

df = pd.read_csv('dataset/autos_imports-85.csv')
# df.columns = headers
df.head()

,%symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

## Data Preprocessing
### What is Missing Value

- Occured when no data value is stored for a variable (feature) in an observation.
- Missing value is represented by '?', 'N/A', 0, or just a blank cell.

### Handling Missing Value 
- Drop the missing values
  - Drop the variable
  - Drop the data entry (preferable)
- Replace the missing value (Recommended)
  - Replace it with an average (of similar datapoints)
  - Replace it by frequency (mode)
  - Replace it based on other functions
- Leave it as missing data

In [89]:
df.head()

,%symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

#### Replace Missing Value Identifier 

Notice that we have "?" as the missing value identifier. We need to replace it with "None" so that we can identify missing values using `.isna()`

In [107]:
df.replace('?', np.nan, inplace=True)
df.head()

,%symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [108]:
columns = df.columns.to_list()
for col in columns:
  print(df[col].isna().value_counts())

%symboling
False    205
Name: count, dtype: int64
normalized-losses
False    164
True      41
Name: count, dtype: int64
make
False    205
Name: count, dtype: int64
fuel-type
False    205
Name: count, dtype: int64
aspiration
False    205
Name: count, dtype: int64
num-of-doors
False    203
True       2
Name: count, dtype: int64
body-style
False    205
Name: count, dtype: int64
drive-wheels
False    205
Name: count, dtype: int64
engine-location
False    205
Name: count, dtype: int64
 wheel-base
False    205
Name: count, dtype: int64
length
False    205
Name: count, dtype: int64
width
False    205
Name: count, dtype: int64
height
False    205
Name: count, dtype: int64
curb-weight
False    205
Name: count, dtype: int64
engine-type
False    205
Name: count, dtype: int64
num-of-cylinders
False    205
Name: count, dtype: int64
engine-size
False    205
Name: count, dtype: int64
fuel-system
False    205
Name: count, dtype: int64
bore
False    201
True       4
Name: count, dtype: int64
stroke
False    201
True       4
Name: count, dtype: int64
compression-ratio
False    205
Name: count, dtype: int64
horsepower
False    203
True       2
Name: count, dtype: int64
peak-rpm
False    203
True       2
Name: count, dtype: int64
city-mpg
False    205
Name: count, dtype: int64
highway-mpg
False    205
Name: count, dtype: int64
price
False    201
True       4
Name: count, dtype: int64

#### Drop the Missing Values

Now, we have 4 missing values in the price columns. Let's drop it!

In [109]:
# Drop the missing value
df_master = df.dropna(subset= ['price'], axis=0)
df_master.head()

,%symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

#### Replace the Missing Values with Mean

In [110]:
df.columns.to_list()

['%symboling',
 'normalized-losses',
 'make',
 'fuel-type',
 'aspiration',
 'num-of-doors',
 'body-style',
 'drive-wheels',
 'engine-location',
 ' wheel-base',
 'length',
 'width',
 'height',
 'curb-weight',
 'engine-type',
 'num-of-cylinders',
 'engine-size',
 'fuel-system',
 'bore',
 'stroke',
 'compression-ratio',
 'horsepower',
 'peak-rpm',
 'city-mpg',
 'highway-mpg',
 'price']

In [112]:
# Let's change the data type for numerical columns
num_columns = ['normalized-losses', ' wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-size',  'bore', 'stroke', 'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg', 'highway-mpg', 'price']
# num_columns = ['normalized-losses']
for col in num_columns:
  df_master[col] = df_master[col].astype(np.float64)
# df_master['normalized-losses'] = df_master['normalized-losses'].astype('Int64')
df_master.info()

<class 'pandas.core.frame.DataFrame'>
Index: 201 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   %symboling         201 non-null    int64
 1   normalized-losses  164 non-null    float64
 2   make               201 non-null    object
 3   fuel-type          201 non-null    object
 4   aspiration         201 non-null    object
 5   num-of-doors       199 non-null    object
 6   body-style         201 non-null    object
 7   drive-wheels       201 non-null    object
 8   engine-location    201 non-null    object
 9    wheel-base        201 non-null    float64
 10  length             201 non-null    float64
 11  width              201 non-null    float64
 12  height             201 non-null    float64
 13  curb-weight        201 non-null    float64
 14  engine-type        201 non-null    object
 15  num-of-cylinders   201 non-null    object
 16  engine-size        201 non-null    float64
 17  fuel-system        201 non-null    object
 18  bore               197 non-null    float64
 19  stroke             197 non-null    float64
 20  compression-ratio  201 non-null    float64
 21  horsepower         199 non-null    float64
 22  peak-rpm           199 non-null    float64
 23  city-mpg           201 non-null    float64
 24  highway-mpg        201 non-null    float64
 25  price              201 non-null    float64
dtypes: float64(15), int64(1), object(10)
memory usage: 42.4+ KB

/var/folders/vm/3txrml4d02zch5_v8m3tqwnr0000gp/T/ipykernel_48325/3500289424.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_master[col] = df_master[col].astype(np.float64)
/var/folders/vm/3txrml4d02zch5_v8m3tqwnr0000gp/T/ipykernel_48325/3500289424.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_master[col] = df_master[col].astype(np.float64)
/var/folders/vm/3txrml4d02zch5_v8m3tqwnr0000gp/T/ipykernel_48325/3500289424.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_master[col] = df_master[col].astype(np.float64)
/var/folders/vm/3txrml4d02zch5_v8m3tqwnr0000gp/T/ipykernel_48325/3500289424.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_master[col] = df_master[col].astype(np.float64)
/var/folders/vm/3txrml4d02zch5_v8m3tqwnr0000gp/T/ipykernel_48325/3500289424.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_master[col] = df_master[col].astype(np.float64)
/var/folders/vm/3txrml4d02zch5_v8m3tqwnr0000gp/T/ipykernel_48325/3500289424.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_master[col] = df_master[col].astype(np.float64)
/var/folders/vm/3txrml4d02zch5_v8m3tqwnr0000gp/T/ipykernel_48325/3500289424.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_master[col] = df_master[col].astype(np.float64)
/var/folders/vm/3txrml4d02zch5_v8m3tqwnr0000gp/T/ipykernel_48325/3500289424.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_master[col] = df_master[col].astype(np.float64)
/var/folders/vm/3txrml4d02zch5_v8m3tqwnr0000gp/T/ipykernel_48325/3500289424.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_master[col] = df_master[col].astype(np.float64)
/var/folders/vm/3txrml4d02zch5_v8m3tqwnr0000gp/T/ipykernel_48325/3500289424.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_master[col] = df_master[col].astype(np.float64)
/var/folders/vm/3txrml4d02zch5_v8m3tqwnr0000gp/T/ipykernel_48325/3500289424.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_master[col] = df_master[col].astype(np.float64)
/var/folders/vm/3txrml4d02zch5_v8m3tqwnr0000gp/T/ipykernel_48325/3500289424.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_master[col] = df_master[col].astype(np.float64)
/var/folders/vm/3txrml4d02zch5_v8m3tqwnr0000gp/T/ipykernel_48325/3500289424.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_master[col] = df_master[col].astype(np.float64)
/var/folders/vm/3txrml4d02zch5_v8m3tqwnr0000gp/T/ipykernel_48325/3500289424.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_master[col] = df_master[col].astype(np.float64)
/var/folders/vm/3txrml4d02zch5_v8m3tqwnr0000gp/T/ipykernel_48325/3500289424.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_master[col] = df_master[col].astype(np.float64)

In [113]:
df_master.head()

,%symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130.0,mpfi,3.47,2.68,9.0,111.0,5000.0,21.0,27.0,13495.0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130.0,mpfi,3.47,2.68,9.0,111.0,5000.0,21.0,27.0,16500.0
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152.0,mpfi,2.68,3.47,9.0,154.0,5000.0,19.0,26.0,16500.0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109.0,mpfi,3.19,3.40,10.0,102.0,5500.0,24.0,30.0,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136.0,mpfi,3.19,3.40,8.0,115.0,5500.0,18.0,22.0,17450.0

In [114]:
mean = df_master['normalized-losses'].mean()
df_master['normalized-losses'].fillna(mean, inplace=True)
df_master.head()

/var/folders/vm/3txrml4d02zch5_v8m3tqwnr0000gp/T/ipykernel_48325/3917679688.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_master['normalized-losses'].fillna(mean, inplace=True)

,%symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130.0,mpfi,3.47,2.68,9.0,111.0,5000.0,21.0,27.0,13495.0
1,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130.0,mpfi,3.47,2.68,9.0,111.0,5000.0,21.0,27.0,16500.0
2,1,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152.0,mpfi,2.68,3.47,9.0,154.0,5000.0,19.0,26.0,16500.0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109.0,mpfi,3.19,3.40,10.0,102.0,5500.0,24.0,30.0,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136.0,mpfi,3.19,3.40,8.0,115.0,5500.0,18.0,22.0,17450.0